### ISSUE TITLE
[BUG] - unknown column on wrong field delimiter

### ISSUE THREAD

**Issue by NobodyForNothing** [NobodyForNothing/blood-pressure-monitor-fl#225]
### Description

When the field delimiter is set to '|' and the import of a csv file with the ',' delimiter is selected for input no error message is shown on screen, although an exception is thrown in development mode.

<details><summary>Error</summary>
<p>

E/flutter ( 4505): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Unknown column: timestampUnixMs,systolic,diastolic,pulse,notes,color
E/flutter ( 4505): #0      ExportFileCreator.parseCSVFile (package:blood_pressure_app/model/export_import.dart:104:11)
E/flutter ( 4505): #1      ExportFileCreator.parseFile (package:blood_pressure_app/model/export_import.dart:58:18)
E/flutter ( 4505): #2      Exporter.import (package:blood_pressure_app/model/export_import.dart:323:52)
E/flutter ( 4505): <asynchronous suspension>

</p>
</details>

**Comment by NobodyForNothing** [comment]
fixed in #248
